# Generated by Django 6.0.5 on 2026-09-10 11:43

import django.core.validators
import django.db.models.deletion
import homepage.portfolio.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("hero_heading", models.CharField(max_length=120)),
                ("hero_intro", models.TextField(blank=True)),
                ("about_heading", models.CharField(default="Über mich", max_length=120)),
                ("about_text", wagtail.fields.RichTextField(blank=True)),
                ("contact_heading", models.CharField(default="Lass uns sprechen", max_length=120)),
                ("contact_email", models.EmailField(max_length=254)),
            ],
            options={
                "abstract": False,
            },
            bases=(homepage.portfolio.models.PortfolioContextMixin, "wagtailcore.page"),
        ),
        migrations.CreateModel(
            name="ProjectPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("teaser_text", models.TextField(max_length=320)),
                (
                    "category",
                    models.CharField(
                        choices=[("web", "Web"), ("print", "Print"), ("illustration", "Illustration")], max_length=20
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(homepage.portfolio.models.current_year),
                        ]
                    ),
                ),
                (
                    "services",
                    models.CharField(
                        help_text="Kommagetrennte Leistungen, zum Beispiel: Webdesign, UX", max_length=240
                    ),
                ),
                ("live_url", models.URLField(blank=True)),
                ("body", wagtail.fields.RichTextField(blank=True)),
                (
                    "teaser_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(homepage.portfolio.models.PortfolioContextMixin, "wagtailcore.page"),
        ),
    ]
