# Generated by Django 6.1.1 on 2026-09-29 21:10

import django.core.validators
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.conf import settings
from django.db import migrations, models

import homepage.portfolio.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0098_apitoken"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80, unique=True, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Projektkategorie",
                "verbose_name_plural": "Projektkategorien",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ErrorPageSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "headline",
                    models.CharField(
                        default="Ablage P.",
                        help_text="Kurze Überschrift mit höchstens drei Wörtern.",
                        max_length=120,
                        validators=[homepage.portfolio.models.validate_max_three_words],
                        verbose_name="Überschrift",
                    ),
                ),
                (
                    "sentence",
                    models.CharField(
                        default="Diese Idee hat es leider nicht weiter geschafft. Also zurück ans Zeichenbrett. Du könntest dir so lange diese Projekte anschauen.",
                        max_length=240,
                        verbose_name="Satz",
                    ),
                ),
                ("code_label", models.CharField(default="Fehler 501", max_length=80, verbose_name="Fehlerkennung")),
                (
                    "featured_projects_heading",
                    models.CharField(
                        default="Projekte zum Weitersehen",
                        max_length=160,
                        verbose_name="Überschrift der Projektempfehlungen",
                    ),
                ),
                (
                    "home_link_label",
                    models.CharField(
                        default="Zur Startseite", max_length=120, verbose_name="Beschriftung des Startseitenlinks"
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False, on_delete=django.db.models.deletion.CASCADE, to="wagtailcore.site"
                    ),
                ),
            ],
            options={
                "verbose_name": "501-Seite",
            },
        ),
        migrations.CreateModel(
            name="LegalPageSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("eyebrow", models.CharField(default="Rechtliches", max_length=120, verbose_name="Rubrik")),
                (
                    "imprint_title",
                    models.CharField(default="Impressum", max_length=120, verbose_name="Impressum: Seitentitel"),
                ),
                (
                    "imprint_sections",
                    wagtail.fields.StreamField(
                        [("section", 9)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"label": "Überschrift", "max_length": 160}),
                            1: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"features": ["bold", "italic", "link", "no-break"], "label": "Absatz"},
                            ),
                            2: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"features": ["bold", "italic", "link", "no-break"], "label": "Adresse"},
                            ),
                            3: ("wagtail.blocks.CharBlock", (), {"label": "Stand oder Hinweis", "max_length": 240}),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Zum Beispiel „E-Mail:“; Abstand und globale Adresse werden automatisch ergänzt.",
                                    "label": "Text vor dem Link",
                                    "max_length": 240,
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Leer lassen, um die globale Kontaktadresse sichtbar auszugeben.",
                                    "label": "Abweichender Linktext",
                                    "max_length": 160,
                                    "required": False,
                                },
                            ),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Zum Beispiel ein abschließender Punkt.",
                                    "label": "Text nach dem Link",
                                    "max_length": 120,
                                    "required": False,
                                },
                            ),
                            7: ("wagtail.blocks.StructBlock", [[("prefix", 4), ("label", 5), ("suffix", 6)]], {}),
                            8: (
                                "wagtail.blocks.StreamBlock",
                                [[("paragraph", 1), ("address", 2), ("note", 3), ("contact", 7)]],
                                {"label": "Text"},
                            ),
                            9: ("wagtail.blocks.StructBlock", [[("heading", 0), ("copy", 8)]], {}),
                        },
                        default=homepage.portfolio.models.default_imprint_sections,
                        verbose_name="Impressum: Abschnitte",
                    ),
                ),
                (
                    "imprint_visual_label",
                    models.CharField(
                        default="Illustrationsmotiv",
                        help_text="Alternativtext des gewählten Bildes und sichtbare Beschriftung des grafischen Platzhalters.",
                        max_length=160,
                        verbose_name="Impressum: Bildbeschreibung",
                    ),
                ),
                (
                    "privacy_title",
                    models.CharField(default="Datenschutz", max_length=120, verbose_name="Datenschutz: Seitentitel"),
                ),
                (
                    "privacy_sections",
                    wagtail.fields.StreamField(
                        [("section", 9)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"label": "Überschrift", "max_length": 160}),
                            1: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"features": ["bold", "italic", "link", "no-break"], "label": "Absatz"},
                            ),
                            2: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"features": ["bold", "italic", "link", "no-break"], "label": "Adresse"},
                            ),
                            3: ("wagtail.blocks.CharBlock", (), {"label": "Stand oder Hinweis", "max_length": 240}),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Zum Beispiel „E-Mail:“; Abstand und globale Adresse werden automatisch ergänzt.",
                                    "label": "Text vor dem Link",
                                    "max_length": 240,
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Leer lassen, um die globale Kontaktadresse sichtbar auszugeben.",
                                    "label": "Abweichender Linktext",
                                    "max_length": 160,
                                    "required": False,
                                },
                            ),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Zum Beispiel ein abschließender Punkt.",
                                    "label": "Text nach dem Link",
                                    "max_length": 120,
                                    "required": False,
                                },
                            ),
                            7: ("wagtail.blocks.StructBlock", [[("prefix", 4), ("label", 5), ("suffix", 6)]], {}),
                            8: (
                                "wagtail.blocks.StreamBlock",
                                [[("paragraph", 1), ("address", 2), ("note", 3), ("contact", 7)]],
                                {"label": "Text"},
                            ),
                            9: ("wagtail.blocks.StructBlock", [[("heading", 0), ("copy", 8)]], {}),
                        },
                        default=homepage.portfolio.models.default_privacy_sections,
                        verbose_name="Datenschutz: Abschnitte",
                    ),
                ),
                (
                    "imprint_visual_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optionales 4:5-Motiv. Der in der Bildverwaltung gesetzte Fokuspunkt wird beim Ausschnitt berücksichtigt; ohne Bild bleibt der grafische Platzhalter.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Impressum: Illustration",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False, on_delete=django.db.models.deletion.CASCADE, to="wagtailcore.site"
                    ),
                ),
            ],
            options={
                "verbose_name": "Portfolio-Rechtsseiten",
            },
        ),
        migrations.CreateModel(
            name="PortfolioIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.WAGTAIL_PAGE_MODEL,
                    ),
                ),
                ("hero_heading", models.CharField(default="Moin", editable=False, max_length=120)),
                (
                    "hero_intro_emphasis",
                    models.CharField(
                        default="Web & Digital Design ist mein Zuhause",
                        max_length=200,
                        verbose_name="Hervorgehobener Einstieg",
                    ),
                ),
                ("hero_intro", models.TextField(blank=True)),
                (
                    "hero_intro_secondary",
                    models.TextField(
                        blank=True,
                        default="Ich denke über Medien hinweg – damit Gestaltung genau dort funktioniert, wo sie gebraucht wird.",
                        verbose_name="Zweiter Einstiegsabsatz",
                    ),
                ),
                (
                    "hero_note_heading",
                    models.CharField(
                        default="15+ years in branding.", max_length=120, verbose_name="Erfahrungsvermerk"
                    ),
                ),
                (
                    "hero_note_text",
                    models.CharField(
                        default="Zwischen Kopfkino, Konzept\xa0und\xa0Feinschliff.",
                        max_length=200,
                        verbose_name="Text zum Erfahrungsvermerk",
                    ),
                ),
                ("projects_eyebrow", models.CharField(default="Ein kleiner Einblick", max_length=120)),
                ("projects_heading", models.CharField(default="Projekte", max_length=120)),
                ("projects_annotation", models.CharField(default="recent work", editable=False, max_length=120)),
                ("project_inquiry_label", models.CharField(default="Projekt anfragen", max_length=120)),
                ("services_eyebrow", models.CharField(default="Was ich anbiete", max_length=120)),
                ("services_heading", models.CharField(default="Leistungen", max_length=120)),
                ("services_annotation", models.CharField(default="let's talk about", editable=False, max_length=120)),
                ("about_eyebrow", models.CharField(default="Wie ich arbeite", max_length=120)),
                ("about_statement_intro", models.CharField(default="Ich bin", max_length=120)),
                ("about_name", models.CharField(default="Katharina", max_length=120)),
                ("about_statement_outro", models.CharField(default="und bleibe gern neugierig.", max_length=160)),
                ("about_annotation", models.CharField(default="that's me", editable=False, max_length=120)),
                ("about_claim", models.CharField(default="Digital Creative · Based in Düsseldorf", max_length=160)),
                (
                    "about_portrait_image_alt",
                    models.CharField(
                        blank=True,
                        help_text="Beschreibt den Bildinhalt knapp für Menschen, die das Bild nicht sehen können.",
                        max_length=240,
                        verbose_name="Alternativtext des Porträts",
                    ),
                ),
                ("resume_label", models.CharField(default="Lebenslauf anfragen", max_length=120)),
                ("clients_eyebrow", models.CharField(default="Über die Jahre", max_length=120)),
                ("clients_heading", models.CharField(default="Mit diesen Marken", max_length=160)),
                ("clients_heading_secondary", models.CharField(default="& Menschen", max_length=160)),
                ("clients_annotation", models.CharField(default="together", editable=False, max_length=120)),
                ("contact_eyebrow", models.CharField(default="Auf ein Wort", max_length=120)),
                ("contact_heading_primary", models.CharField(default="Ein Projekt im Kopf?", max_length=160)),
                ("contact_heading_secondary", models.CharField(default="Schreib", max_length=160)),
                ("contact_heading_emphasis", models.CharField(default="mir.", max_length=80)),
                ("contact_annotation", models.CharField(default="tell me more", editable=False, max_length=120)),
                ("contact_cta_label", models.CharField(default="E-Mail schreiben", max_length=120)),
                (
                    "about_portrait_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Bild für den Porträtklecks. Der in der Bildverwaltung gesetzte Fokuspunkt wird beim 4:5-Ausschnitt berücksichtigt.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Porträt",
                    ),
                ),
                (
                    "hero_background_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optionales Motiv für den farbigen Reveal hinter ‚MOIN‘. Der in der Bildverwaltung gesetzte Fokuspunkt steuert die Desktop- und Mobile-Ausschnitte. Ohne Auswahl bleibt die freigegebene generierte Illustration erhalten.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Hero-Hintergrundbild",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(homepage.portfolio.models.PortfolioContextMixin, "wagtailcore.page"),
        ),
        migrations.CreateModel(
            name="PortfolioClient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                ("name", models.CharField(max_length=160)),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clients",
                        to="portfolio.portfolioindexpage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PortfolioAboutItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                ("title", models.CharField(max_length=120)),
                ("lead", models.CharField(max_length=240)),
                ("text", models.TextField()),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="about_items",
                        to="portfolio.portfolioindexpage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PortfolioService",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("web", "Webdesign"),
                            ("product", "Product Design"),
                            ("graphic", "Grafikdesign"),
                            ("branding", "Branding"),
                            ("illustration", "Illustration"),
                            ("packaging", "Verpackung"),
                            ("campaign", "Campaigning"),
                            ("ai", "KI-Workflows"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("description", models.CharField(max_length=320)),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homepage_services",
                        to="portfolio.portfolioindexpage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PortfolioSiteSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("brand_name", models.CharField(default="Katharina Wersdörfer", max_length=120, verbose_name="Name")),
                (
                    "availability_text",
                    models.CharField(
                        default="Verfügbar für Projekte", max_length=120, verbose_name="Verfügbarkeitstext"
                    ),
                ),
                ("show_availability", models.BooleanField(default=True, verbose_name="Verfügbarkeit anzeigen")),
                (
                    "profile_text",
                    models.CharField(
                        default="Web & Digital Design, Illustration und Print — aus Düsseldorf.",
                        max_length=240,
                        verbose_name="Kurzprofil",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        default="katharina@wersdoerfer.de",
                        help_text="Einzige öffentliche E-Mail-Quelle für Header, Menü, Startseite, Projektseiten und Rechtstexte.",
                        max_length=254,
                        verbose_name="Kontaktadresse",
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(
                        blank=True,
                        default="https://www.linkedin.com/in/katharina-wersd%C3%B6rfer-7a41181a2",
                        verbose_name="LinkedIn",
                    ),
                ),
                (
                    "github_url",
                    models.URLField(blank=True, default="https://github.com/federfuxx", verbose_name="GitHub"),
                ),
                (
                    "mastodon_url",
                    models.URLField(
                        blank=True, default="https://fedi.wersdoerfer.de/@katharina", verbose_name="Mastodon"
                    ),
                ),
                (
                    "copyright_text",
                    models.CharField(default="© 2026 Katharina Wersdörfer", max_length=160, verbose_name="Copyright"),
                ),
                (
                    "location_text",
                    models.CharField(default="Designed in Düsseldorf", max_length=160, verbose_name="Ortszeile"),
                ),
                ("contact_label", models.CharField(default="Kontakt", max_length=80, verbose_name="Kontakt")),
                ("projects_label", models.CharField(default="Projekte", max_length=80, verbose_name="Projekte")),
                (
                    "all_projects_label",
                    models.CharField(default="Alle Projekte", max_length=120, verbose_name="Alle Projekte"),
                ),
                ("services_label", models.CharField(default="Leistungen", max_length=80, verbose_name="Leistungen")),
                ("about_label", models.CharField(default="Über mich", max_length=80, verbose_name="Über mich")),
                ("clients_label", models.CharField(default="Kunden", max_length=80, verbose_name="Kunden")),
                ("case_study_label", models.CharField(default="Case Study", max_length=80, verbose_name="Case Study")),
                ("gallery_label", models.CharField(default="Galerie", max_length=80, verbose_name="Galerie")),
                ("results_label", models.CharField(default="Mehrwert", max_length=80, verbose_name="Mehrwert")),
                (
                    "footer_pages_heading",
                    models.CharField(default="Seite", max_length=80, verbose_name="Footer: Seitenüberschrift"),
                ),
                (
                    "project_kicker",
                    models.CharField(default="Projekt", max_length=80, verbose_name="Projekt: Zählerbezeichnung"),
                ),
                (
                    "project_meta_category_label",
                    models.CharField(default="Bereich", max_length=80, verbose_name="Projekt: Bereich"),
                ),
                (
                    "project_meta_year_label",
                    models.CharField(default="Jahr", max_length=80, verbose_name="Projekt: Jahr"),
                ),
                (
                    "project_meta_client_label",
                    models.CharField(default="Kunde", max_length=80, verbose_name="Projekt: Kunde"),
                ),
                (
                    "project_meta_services_label",
                    models.CharField(default="Leistungen", max_length=80, verbose_name="Projekt: Leistungen"),
                ),
                (
                    "project_live_link_label",
                    models.CharField(
                        default="Website ansehen", max_length=120, verbose_name="Projekt: Link zur Website"
                    ),
                ),
                (
                    "project_statement_heading",
                    models.CharField(
                        default="Das Projekt", max_length=120, verbose_name="Projekt: Statement-Überschrift"
                    ),
                ),
                (
                    "project_challenge_heading",
                    models.CharField(
                        default="Die Aufgabe", max_length=120, verbose_name="Projekt: Aufgaben-Überschrift"
                    ),
                ),
                (
                    "project_solution_heading",
                    models.CharField(
                        default="Die Lösung", max_length=120, verbose_name="Projekt: Lösungs-Überschrift"
                    ),
                ),
                (
                    "project_results_heading",
                    models.CharField(
                        default="Was bleibt.", max_length=120, verbose_name="Projekt: Mehrwert-Überschrift"
                    ),
                ),
                (
                    "project_testimonial_label",
                    models.CharField(
                        default="Kundenstimmen", max_length=120, verbose_name="Projekt: Kundenstimmen-Rubrik"
                    ),
                ),
                (
                    "related_projects_eyebrow",
                    models.CharField(
                        default="Weitere Projekte", max_length=120, verbose_name="Weitere Projekte: Rubrik"
                    ),
                ),
                (
                    "related_projects_heading",
                    models.CharField(
                        default="Weiterse\xadhen.", max_length=120, verbose_name="Weitere Projekte: Überschrift"
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False, on_delete=django.db.models.deletion.CASCADE, to="wagtailcore.site"
                    ),
                ),
            ],
            options={
                "verbose_name": "Portfolio-Site",
            },
        ),
        migrations.CreateModel(
            name="ProjectPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.WAGTAIL_PAGE_MODEL,
                    ),
                ),
                (
                    "teaser_text",
                    wagtail.fields.RichTextField(
                        help_text="Kurzer Projektteaser; Hervorhebungen können fett gesetzt, verlinkt oder mit ‚Kein Umbruch‘ als zusammenhängender Begriff geschützt werden.",
                        max_length=320,
                        verbose_name="Teasertext",
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        help_text="Bei einem Zeitraum das erste Jahr eintragen.",
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(homepage.portfolio.models.current_year),
                        ],
                        verbose_name="Jahr / Startjahr",
                    ),
                ),
                (
                    "end_year",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Nur bei mehrjährigen Projekten ausfüllen. Die Ausgabe erfolgt automatisch als Zeitraum, zum Beispiel 2021–2024.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(homepage.portfolio.models.current_year),
                        ],
                        verbose_name="Endjahr (optional)",
                    ),
                ),
                (
                    "homepage_is_hero",
                    models.BooleanField(
                        default=False,
                        help_text="Stellt das Projekt im Desktop-Raster groß und quer im Format 21:9 dar. Mobil bleibt das erste Projekt der sortierten Reihenfolge der große 16:9-Einstieg; alle weiteren Projekte laufen im einheitlichen Reel.",
                        verbose_name="Hero-Kachel auf der Startseite",
                    ),
                ),
                ("client", models.CharField(blank=True, max_length=160, verbose_name="Kunde")),
                ("live_url", models.URLField(blank=True)),
                (
                    "live_link_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optionaler Text für den Link zur Projektwebsite. Leer lassen, um den globalen Standard zu verwenden.",
                        max_length=120,
                        verbose_name="Text des Website-Buttons",
                    ),
                ),
                (
                    "teaser_image_alt",
                    models.CharField(
                        blank=True,
                        help_text="Beschreibt den Bildinhalt knapp für Menschen, die das Bild nicht sehen können.",
                        max_length=240,
                        verbose_name="Alternativtext des Teaserbilds",
                    ),
                ),
                (
                    "hero_image_alt",
                    models.CharField(
                        blank=True,
                        help_text="Beschreibt den Bildinhalt knapp für Menschen, die das Bild nicht sehen können.",
                        max_length=240,
                        verbose_name="Alternativtext des Projekt-Heros",
                    ),
                ),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [
                            ("statement", 1),
                            ("challenge_solution", 4),
                            ("full_width_image", 7),
                            ("image_pair", 10),
                            ("portrait_duo", 10),
                            ("gallery", 14),
                            ("stats", 19),
                            ("testimonial", 23),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"features": ["bold", "italic", "link", "no-break"], "label": "Text"},
                            ),
                            1: ("wagtail.blocks.StructBlock", [[("text", 0)]], {}),
                            2: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"features": ["bold", "italic", "ol", "ul", "link", "no-break"], "label": "Aufgabe"},
                            ),
                            3: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"features": ["bold", "italic", "ol", "ul", "link", "no-break"], "label": "Lösung"},
                            ),
                            4: ("wagtail.blocks.StructBlock", [[("challenge", 2), ("solution", 3)]], {}),
                            5: ("wagtail.images.blocks.ImageBlock", [], {"label": "Bild"}),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Bildunterschrift", "max_length": 240, "required": False},
                            ),
                            7: ("wagtail.blocks.StructBlock", [[("image", 5), ("caption", 6)]], {}),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 5), ("caption", 6)]],
                                {"label": "Bild links"},
                            ),
                            9: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 5), ("caption", 6)]],
                                {"label": "Bild rechts"},
                            ),
                            10: ("wagtail.blocks.StructBlock", [[("left", 8), ("right", 9)]], {}),
                            11: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Beginnt eine eigene, vollbreite Galeriezeile.",
                                    "label": "Großes Motiv",
                                    "required": False,
                                },
                            ),
                            12: ("wagtail.blocks.StructBlock", [[("image", 5), ("caption", 6), ("large", 11)]], {}),
                            13: (
                                "wagtail.blocks.ListBlock",
                                (12,),
                                {
                                    "help_text": "Mindestens zwei Bilder; die Reihenfolge kann frei geändert werden.",
                                    "label": "Bilder",
                                    "min_num": 2,
                                },
                            ),
                            14: ("wagtail.blocks.StructBlock", [[("images", 13)]], {}),
                            15: ("wagtail.blocks.CharBlock", (), {"label": "Wert", "max_length": 80}),
                            16: ("wagtail.blocks.CharBlock", (), {"label": "Bezeichnung", "max_length": 160}),
                            17: ("wagtail.blocks.StructBlock", [[("value", 15), ("label", 16)]], {}),
                            18: ("wagtail.blocks.ListBlock", (17,), {"label": "Mehrwert", "min_num": 1}),
                            19: ("wagtail.blocks.StructBlock", [[("items", 18)]], {}),
                            20: ("wagtail.blocks.TextBlock", (), {"label": "Zitat"}),
                            21: ("wagtail.blocks.CharBlock", (), {"label": "Name", "max_length": 120}),
                            22: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Rolle", "max_length": 160, "required": False},
                            ),
                            23: ("wagtail.blocks.StructBlock", [[("quote", 20), ("name", 21), ("role", 22)]], {}),
                        },
                        default=homepage.portfolio.models.default_project_content,
                        verbose_name="Projektinhalt",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Zentrale Projektkategorie. Neue Kategorien können direkt im Auswahlfenster oder über ‚Projekte → Kategorien‘ angelegt werden.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="portfolio.projectcategory",
                        verbose_name="Bereich",
                    ),
                ),
                (
                    "hero_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Während der Datenmigration noch optional; vor dem finalen Launch erforderlich machen.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Projekt-Hero",
                    ),
                ),
                (
                    "teaser_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Während der Datenmigration noch optional; vor dem finalen Launch erforderlich machen.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(homepage.portfolio.models.PortfolioContextMixin, "wagtailcore.page"),
        ),
        migrations.CreateModel(
            name="ProjectService",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                ("name", models.CharField(max_length=240, verbose_name="Leistung")),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_items",
                        to="portfolio.projectpage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
