# Generated by Django 6.0.5 on 2026-09-10

import django.db.models.deletion
import homepage.portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ErrorPageSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                (
                    "headline",
                    models.CharField(
                        default="Ablage P.",
                        help_text="Kurze Überschrift mit höchstens drei Wörtern.",
                        max_length=120,
                        validators=[homepage.portfolio.models.validate_max_three_words],
                        verbose_name="Überschrift",
                    ),
                ),
                (
                    "sentence",
                    models.CharField(
                        default=(
                            "Diese Idee hat es leider nicht weiter geschafft. Also zurück ans Zeichenbrett. "
                            "Du könntest dir so lange diese Projekte anschauen."
                        ),
                        max_length=240,
                        verbose_name="Satz",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "501-Seite",
                "abstract": False,
            },
        ),
    ]
