# Generated by Django 6.0.5 on 2026-09-10

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_errorpagesettings"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectpage",
            name="client",
            field=models.CharField(blank=True, max_length=160, verbose_name="Kunde"),
        ),
        migrations.AddField(
            model_name="projectpage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("statement", 1),
                    ("challenge_solution", 4),
                    ("full_width_image", 7),
                    ("image_pair", 10),
                    ("portrait_duo", 10),
                    ("gallery", 14),
                    ("stats", 19),
                    ("testimonial", 23),
                ],
                blank=True,
                block_counts={
                    "statement": {"max_num": 1},
                    "challenge_solution": {"max_num": 1},
                    "stats": {"max_num": 1},
                    "testimonial": {"max_num": 1},
                },
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link"], "label": "Text"},
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("text", 0)]], {}),
                    2: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic", "ol", "ul", "link"], "label": "Aufgabe"},
                    ),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic", "ol", "ul", "link"], "label": "Lösung"},
                    ),
                    4: ("wagtail.blocks.StructBlock", [[("challenge", 2), ("solution", 3)]], {}),
                    5: ("wagtail.images.blocks.ImageBlock", [], {"label": "Bild"}),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Bildunterschrift", "max_length": 240, "required": False},
                    ),
                    7: ("wagtail.blocks.StructBlock", [[("image", 5), ("caption", 6)]], {}),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 5), ("caption", 6)]],
                        {"label": "Bild links"},
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 5), ("caption", 6)]],
                        {"label": "Bild rechts"},
                    ),
                    10: ("wagtail.blocks.StructBlock", [[("left", 8), ("right", 9)]], {}),
                    11: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Beginnt eine eigene, vollbreite Galeriezeile.",
                            "label": "Großes Motiv",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 5), ("caption", 6), ("large", 11)]],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.ListBlock",
                        (12,),
                        {
                            "help_text": "Mindestens zwei Bilder; die Reihenfolge kann frei geändert werden.",
                            "label": "Bilder",
                            "min_num": 2,
                        },
                    ),
                    14: ("wagtail.blocks.StructBlock", [[("images", 13)]], {}),
                    15: ("wagtail.blocks.CharBlock", (), {"label": "Wert", "max_length": 80}),
                    16: ("wagtail.blocks.CharBlock", (), {"label": "Bezeichnung", "max_length": 160}),
                    17: ("wagtail.blocks.StructBlock", [[("value", 15), ("label", 16)]], {}),
                    18: ("wagtail.blocks.ListBlock", (17,), {"label": "Ergebnisse", "min_num": 1}),
                    19: ("wagtail.blocks.StructBlock", [[("items", 18)]], {}),
                    20: ("wagtail.blocks.TextBlock", (), {"label": "Zitat"}),
                    21: ("wagtail.blocks.CharBlock", (), {"label": "Name", "max_length": 120}),
                    22: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Rolle", "max_length": 160, "required": False},
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 20), ("name", 21), ("role", 22)]],
                        {},
                    ),
                },
                verbose_name="Projektinhalt",
            ),
        ),
        migrations.AddField(
            model_name="projectpage",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Während der Datenmigration noch optional; vor dem finalen Launch erforderlich machen.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Projekt-Hero",
            ),
        ),
        migrations.AddField(
            model_name="projectpage",
            name="hero_image_alt",
            field=models.CharField(
                blank=True,
                help_text="Beschreibt den Bildinhalt knapp für Menschen, die das Bild nicht sehen können.",
                max_length=240,
                verbose_name="Alternativtext des Projekt-Heros",
            ),
        ),
        migrations.AddField(
            model_name="projectpage",
            name="teaser_image_alt",
            field=models.CharField(
                blank=True,
                help_text="Beschreibt den Bildinhalt knapp für Menschen, die das Bild nicht sehen können.",
                max_length=240,
                verbose_name="Alternativtext des Teaserbilds",
            ),
        ),
        migrations.AlterField(
            model_name="projectpage",
            name="body",
            field=wagtail.fields.RichTextField(
                blank=True,
                editable=False,
                help_text="Temporäres Altfeld; wird nach der Template-Migration entfernt.",
            ),
        ),
        migrations.AlterField(
            model_name="projectpage",
            name="services",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Temporäres Altfeld; wird nach der Template-Migration entfernt.",
                max_length=240,
            ),
        ),
        migrations.AlterField(
            model_name="projectpage",
            name="teaser_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Während der Datenmigration noch optional; vor dem finalen Launch erforderlich machen.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.CreateModel(
            name="ProjectService",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                ("name", models.CharField(max_length=240, verbose_name="Leistung")),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_items",
                        to="portfolio.projectpage",
                    ),
                ),
            ],
            options={"ordering": ["sort_order"], "abstract": False},
        ),
    ]
