# Generated by Django 6.0.5 on 2026-09-10

import django.db.models.deletion
import homepage.portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_migrate_legacy_project_content"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioSiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("brand_name", models.CharField(default="Katharina Wersdörfer", max_length=120, verbose_name="Name")),
                (
                    "availability_text",
                    models.CharField(default="Verfügbar für Projekte", max_length=120, verbose_name="Verfügbarkeitstext"),
                ),
                ("show_availability", models.BooleanField(default=True, verbose_name="Verfügbarkeit anzeigen")),
                (
                    "profile_text",
                    models.CharField(
                        default="Web & Digital Design, Illustration und Print — aus Düsseldorf.",
                        max_length=240,
                        verbose_name="Kurzprofil",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        default="katharina@wersdoerfer.de",
                        help_text=(
                            "Vor der sichtbaren Shell-Umstellung bleibt die Kontaktadresse auf der "
                            "Portfolio-Startseite für das Frontend maßgeblich."
                        ),
                        max_length=254,
                        verbose_name="Kontaktadresse",
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(
                        blank=True,
                        default="https://www.linkedin.com/in/katharina-wersd%C3%B6rfer-7a41181a2",
                        verbose_name="LinkedIn",
                    ),
                ),
                (
                    "github_url",
                    models.URLField(
                        blank=True,
                        default="https://github.com/federfuxx",
                        verbose_name="GitHub",
                    ),
                ),
                (
                    "mastodon_url",
                    models.URLField(
                        blank=True,
                        default="https://fedi.wersdoerfer.de/@katharina",
                        verbose_name="Mastodon",
                    ),
                ),
                (
                    "imprint_url",
                    models.CharField(
                        default="/impressum/",
                        help_text="Mit / beginnender interner Pfad oder vollständige HTTP(S)-URL.",
                        max_length=255,
                        validators=[homepage.portfolio.models.validate_internal_path_or_http_url],
                        verbose_name="Impressum",
                    ),
                ),
                (
                    "privacy_url",
                    models.CharField(
                        default="/datenschutz/",
                        help_text="Mit / beginnender interner Pfad oder vollständige HTTP(S)-URL.",
                        max_length=255,
                        validators=[homepage.portfolio.models.validate_internal_path_or_http_url],
                        verbose_name="Datenschutz",
                    ),
                ),
                (
                    "copyright_text",
                    models.CharField(default="© 2026 Katharina Wersdörfer", max_length=160, verbose_name="Copyright"),
                ),
                (
                    "location_text",
                    models.CharField(default="Designed in Düsseldorf", max_length=160, verbose_name="Ortszeile"),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Portfolio-Site",
                "abstract": False,
            },
        ),
    ]
