# Generated by Django 6.0.5 on 2026-09-14

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


SERVICES = (
    (
        "web",
        "Webdesign",
        "Von der Idee bis zur fertigen Website\u00a0— Layout, UX/UI und Umsetzung.",
    ),
    (
        "product",
        "Product\u00a0Design",
        "UX/UI für Apps & digitale Produkte\u00a0— im Team, mit dem Designpart bei mir.",
    ),
    (
        "graphic",
        "Grafikdesign",
        "Editorial, Layout und Typografie mit Blick fürs Detail.",
    ),
    (
        "branding",
        "Branding",
        "Logo, Marke und Designsysteme, die Wiedererkennung schaffen.",
    ),
    (
        "illustration",
        "Illustration",
        "Handgemachte Bildwelten\u00a0— mein Schwerpunkt und meine Leidenschaft.",
    ),
    (
        "packaging",
        "Verpackung",
        "Packaging, das im Regal auffällt und die Marke trägt.",
    ),
    (
        "campaign",
        "Campaigning",
        "Kampagnenideen und visuelle Leitkonzepte über alle Kanäle.",
    ),
    (
        "ai",
        "KI-Workflows",
        "KI als Sparringspartner im Prozess\u00a0— von Konzept bis Bildwelt.",
    ),
)

ABOUT_ITEMS = (
    (
        "Verstehen",
        "Marken, Menschen und neue Themen.",
        "Mich interessiert, was eine Marke ausmacht und was Gestaltung für sie leisten kann. "
        "Beruflich ging es im Dialogmarketing los. Die Frage „Für wen ist das gedacht?“ begleitet "
        "mich seitdem. Die Erfahrung aus unterschiedlichen Branchen – von Beauty über Food bis "
        "Retail – hilft mir, mich schnell in dein Thema einzuarbeiten und auch ungewohnte Aufgaben "
        "mit frischem Blick zu lösen.",
    ),
    (
        "Gestalten",
        "Illustration, Medien und die Liebe zum Detail.",
        "Illustration begleitet mich schon den ganzen Weg. Ich denke oft in Bildern – und setze sie "
        "gern selbst um, wenn das Projekt es braucht. Über die Jahre habe ich aus Neugier vieles "
        "ausprobiert und dazugelernt. So kann ich heute einen Auftritt über verschiedene Medien "
        "hinweg gestalten und bis ins Detail ausarbeiten. Dabei habe ich schon beim Entwerfen im "
        "Blick, wie es sich umsetzen lässt.",
    ),
    (
        "Umsetzen",
        "Mit Entwicklung und Netzwerk bis zum fertigen Projekt.",
        "Im Team arbeite ich am liebsten – zum Beispiel mit meinem Mann Jochen. Er kümmert sich um "
        "die Software hinter dem Design, mit Schwerpunkt auf Backend und Machine Learning. Je nach "
        "Aufgabe können wir auch weitere Kollegen aus unserem Netzwerk dazuholen. Gemeinsam bleiben "
        "wir dran, bis wir ein gutes Konzept auch tatsächlich auf die Straße gebracht haben. Kurze "
        "Wege inklusive.",
    ),
)

CLIENTS = (
    "ALDI Nord",
    "Kerrygold",
    "L'Oréal",
    "Thomy",
    "Maybelline",
    "essie",
    "Weight Watchers",
    "Miele",
    "Yokohama",
    "McCann",
    "Marina Adler",
    "Fabian Heis",
    "Villa Kunterbunt e.V.",
    "Ökologische Tierzucht gGmbH",
    "django chat",
    "GGS Lennéstraße",
    "McCann",
)


def seed_homepage_collections(apps, schema_editor):
    PortfolioIndexPage = apps.get_model("portfolio", "PortfolioIndexPage")
    PortfolioService = apps.get_model("portfolio", "PortfolioService")
    PortfolioAboutItem = apps.get_model("portfolio", "PortfolioAboutItem")
    PortfolioClient = apps.get_model("portfolio", "PortfolioClient")
    database = schema_editor.connection.alias

    for page in PortfolioIndexPage.objects.using(database).all():
        if not PortfolioService.objects.using(database).filter(page=page).exists():
            PortfolioService.objects.using(database).bulk_create(
                PortfolioService(
                    page=page,
                    sort_order=index,
                    icon=icon,
                    title=title,
                    description=description,
                )
                for index, (icon, title, description) in enumerate(SERVICES)
            )
        if not PortfolioAboutItem.objects.using(database).filter(page=page).exists():
            PortfolioAboutItem.objects.using(database).bulk_create(
                PortfolioAboutItem(
                    page=page, sort_order=index, title=title, lead=lead, text=text
                )
                for index, (title, lead, text) in enumerate(ABOUT_ITEMS)
            )
        if not PortfolioClient.objects.using(database).filter(page=page).exists():
            PortfolioClient.objects.using(database).bulk_create(
                PortfolioClient(page=page, sort_order=index, name=name)
                for index, name in enumerate(CLIENTS)
            )


class Migration(migrations.Migration):
    dependencies = [("portfolio", "0006_portfolio_hero_copy")]

    operations = [
        migrations.AddField(
            model_name="portfolioindexpage",
            name="about_annotation",
            field=models.CharField(default="that's me", max_length=120),
        ),
        migrations.AddField(
            model_name="portfolioindexpage",
            name="about_claim",
            field=models.CharField(
                default="Digital Creative · Based in Düsseldorf", max_length=160
            ),
        ),
        migrations.AddField(
            model_name="portfolioindexpage",
            name="about_eyebrow",
            field=models.CharField(default="Wie ich arbeite", max_length=120),
        ),
        migrations.AddField(
            model_name="portfolioindexpage",
            name="about_name",
            field=models.CharField(default="Katharina", max_length=120),
        ),
        migrations.AddField(
            model_name="portfolioindexpage",
            name="about_statement_intro",
            field=models.CharField(default="Ich bin", max_length=120),
        ),
        migrations.AddField(
            model_name="portfolioindexpage",
            name="about_statement_outro",
            field=models.CharField(
                default="und bleibe gern neugierig.", max_length=160
            ),
        ),
        migrations.AddField(
            model_name="portfolioindexpage",
            name="clients_annotation",
            field=models.CharField(default="together", max_length=120),
        ),
        migrations.AddField(
            model_name="portfolioindexpage",
            name="clients_eyebrow",
            field=models.CharField(default="Über die Jahre", max_length=120),
        ),
        migrations.AddField(
            model_name="portfolioindexpage",
            name="clients_heading",
            field=models.CharField(default="Mit diesen Marken", max_length=160),
        ),
        migrations.AddField(
            model_name="portfolioindexpage",
            name="clients_heading_secondary",
            field=models.CharField(default="& Menschen", max_length=160),
        ),
        migrations.AddField(
            model_name="portfolioindexpage",
            name="contact_annotation",
            field=models.CharField(default="tell me more", max_length=120),
        ),
        migrations.AddField(
            model_name="portfolioindexpage",
            name="contact_cta_label",
            field=models.CharField(default="E-Mail schreiben", max_length=120),
        ),
        migrations.AddField(
            model_name="portfolioindexpage",
            name="contact_eyebrow",
            field=models.CharField(default="Auf ein Wort", max_length=120),
        ),
        migrations.AddField(
            model_name="portfolioindexpage",
            name="contact_heading_secondary",
            field=models.CharField(default="Schreib mir.", max_length=160),
        ),
        migrations.AddField(
            model_name="portfolioindexpage",
            name="project_inquiry_label",
            field=models.CharField(default="Projekt anfragen", max_length=120),
        ),
        migrations.AddField(
            model_name="portfolioindexpage",
            name="projects_annotation",
            field=models.CharField(default="recent work", max_length=120),
        ),
        migrations.AddField(
            model_name="portfolioindexpage",
            name="projects_eyebrow",
            field=models.CharField(default="Ein kleiner Einblick", max_length=120),
        ),
        migrations.AddField(
            model_name="portfolioindexpage",
            name="projects_heading",
            field=models.CharField(default="Projekte", max_length=120),
        ),
        migrations.AddField(
            model_name="portfolioindexpage",
            name="resume_label",
            field=models.CharField(default="Lebenslauf anfragen", max_length=120),
        ),
        migrations.AddField(
            model_name="portfolioindexpage",
            name="services_annotation",
            field=models.CharField(default="let's talk about", max_length=120),
        ),
        migrations.AddField(
            model_name="portfolioindexpage",
            name="services_eyebrow",
            field=models.CharField(default="Was ich anbiete", max_length=120),
        ),
        migrations.AddField(
            model_name="portfolioindexpage",
            name="services_heading",
            field=models.CharField(default="Leistungen", max_length=120),
        ),
        migrations.AlterField(
            model_name="portfoliositesettings",
            name="contact_email",
            field=models.EmailField(
                default="katharina@wersdoerfer.de",
                help_text=(
                    "Header und Menü verwenden diese gemeinsame Adresse; Startseiteninhalt und "
                    "Footer wechseln im eigenen Paritätspaket vollständig auf diese Quelle."
                ),
                max_length=254,
                verbose_name="Kontaktadresse",
            ),
        ),
        migrations.CreateModel(
            name="PortfolioAboutItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("title", models.CharField(max_length=120)),
                ("lead", models.CharField(max_length=240)),
                ("text", models.TextField()),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="about_items",
                        to="portfolio.portfolioindexpage",
                    ),
                ),
            ],
            options={"ordering": ["sort_order"], "abstract": False},
        ),
        migrations.CreateModel(
            name="PortfolioClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clients",
                        to="portfolio.portfolioindexpage",
                    ),
                ),
            ],
            options={"ordering": ["sort_order"], "abstract": False},
        ),
        migrations.CreateModel(
            name="PortfolioService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("web", "Webdesign"),
                            ("product", "Product Design"),
                            ("graphic", "Grafikdesign"),
                            ("branding", "Branding"),
                            ("illustration", "Illustration"),
                            ("packaging", "Verpackung"),
                            ("campaign", "Campaigning"),
                            ("ai", "KI-Workflows"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("description", models.CharField(max_length=320)),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homepage_services",
                        to="portfolio.portfolioindexpage",
                    ),
                ),
            ],
            options={"ordering": ["sort_order"], "abstract": False},
        ),
        migrations.RunPython(seed_homepage_collections, migrations.RunPython.noop),
    ]
