# Generated by Django 6.0.5 on 2026-09-14

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models

from ._legal_defaults_v1 import (
    default_imprint_sections,
    default_privacy_sections,
)


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0010_portfolio_contact_heading_emphasis"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalPageSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eyebrow",
                    models.CharField(
                        default="Rechtliches",
                        max_length=120,
                        verbose_name="Rubrik",
                    ),
                ),
                (
                    "imprint_title",
                    models.CharField(
                        default="Impressum",
                        max_length=120,
                        verbose_name="Impressum: Seitentitel",
                    ),
                ),
                (
                    "imprint_sections",
                    wagtail.fields.StreamField(
                        [("section", 5)],
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Überschrift", "max_length": 160},
                            ),
                            1: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link"],
                                    "label": "Absatz",
                                },
                            ),
                            2: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link"],
                                    "label": "Adresse",
                                },
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Stand oder Hinweis",
                                    "max_length": 240,
                                },
                            ),
                            4: (
                                "wagtail.blocks.StreamBlock",
                                [[("paragraph", 1), ("address", 2), ("note", 3)]],
                                {"label": "Text"},
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 0), ("copy", 4)]],
                                {},
                            ),
                        },
                        default=default_imprint_sections,
                        verbose_name="Impressum: Abschnitte",
                    ),
                ),
                (
                    "imprint_visual_label",
                    models.CharField(
                        default="Illustrationsmotiv",
                        max_length=160,
                        verbose_name="Impressum: Bildplatzhalter",
                    ),
                ),
                (
                    "privacy_title",
                    models.CharField(
                        default="Datenschutz",
                        max_length=120,
                        verbose_name="Datenschutz: Seitentitel",
                    ),
                ),
                (
                    "privacy_sections",
                    wagtail.fields.StreamField(
                        [("section", 5)],
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Überschrift", "max_length": 160},
                            ),
                            1: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link"],
                                    "label": "Absatz",
                                },
                            ),
                            2: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link"],
                                    "label": "Adresse",
                                },
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Stand oder Hinweis",
                                    "max_length": 240,
                                },
                            ),
                            4: (
                                "wagtail.blocks.StreamBlock",
                                [[("paragraph", 1), ("address", 2), ("note", 3)]],
                                {"label": "Text"},
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 0), ("copy", 4)]],
                                {},
                            ),
                        },
                        default=default_privacy_sections,
                        verbose_name="Datenschutz: Abschnitte",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={"verbose_name": "Portfolio-Rechtsseiten"},
        ),
    ]
