# Generated by Django 6.0.5 on 2026-09-14

from copy import deepcopy
import uuid

from django.db import migrations, models


PROJECT_STARTER_CONTENT = [
    {
        "type": "statement",
        "value": {
            "text": (
                "<p>[Ein prägnanter Satz, der das Projekt und seinen "
                "gestalterischen Kern erklärt.]</p>"
            )
        },
    },
    {
        "type": "challenge_solution",
        "value": {
            "challenge": (
                "<p>[Ausgangslage, Ziel und Rahmenbedingungen. Dieser Bereich "
                "wird später als redaktionelles Wagtail-Feld gepflegt.]</p>"
            ),
            "solution": (
                "<p>[Konzept, gestalterische Entscheidungen und Umsetzung. "
                "Bilder und Textblöcke können im späteren Template einzeln ein- "
                "oder ausgeblendet werden.]</p>"
            ),
        },
    },
]


def project_starter_content():
    """Return fresh serialized blocks with persistent IDs for one project."""

    content = deepcopy(PROJECT_STARTER_CONTENT)
    for block in content:
        block["id"] = str(uuid.uuid4())
    return content


def seed_single_contact_source_and_project_content(apps, schema_editor):
    PortfolioIndexPage = apps.get_model("portfolio", "PortfolioIndexPage")
    PortfolioSiteSettings = apps.get_model("portfolio", "PortfolioSiteSettings")
    ProjectPage = apps.get_model("portfolio", "ProjectPage")
    Site = apps.get_model("wagtailcore", "Site")
    database = schema_editor.connection.alias

    for site in Site.objects.using(database).select_related("root_page"):
        if (
            PortfolioSiteSettings.objects.using(database)
            .filter(site_id=site.pk)
            .exists()
        ):
            continue
        portfolio_index = (
            PortfolioIndexPage.objects.using(database)
            .filter(
                path__startswith=site.root_page.path,
            )
            .order_by("path")
            .first()
        )
        if portfolio_index:
            PortfolioSiteSettings.objects.using(database).create(
                site_id=site.pk,
                contact_email=(
                    portfolio_index.contact_email or "katharina@wersdoerfer.de"
                ),
            )

    for project in ProjectPage.objects.using(database).all():
        if project.content:
            continue
        project.content = project_starter_content()
        project.save(using=database, update_fields=["content"])


class Migration(migrations.Migration):
    dependencies = [("portfolio", "0011_legalpagesettings")]

    operations = [
        migrations.AddField(
            model_name="errorpagesettings",
            name="code_label",
            field=models.CharField(
                default="Fehler 501",
                max_length=80,
                verbose_name="Fehlerkennung",
            ),
        ),
        migrations.AddField(
            model_name="errorpagesettings",
            name="featured_projects_heading",
            field=models.CharField(
                default="Projekte zum Weitersehen",
                max_length=160,
                verbose_name="Überschrift der Projektempfehlungen",
            ),
        ),
        migrations.AddField(
            model_name="errorpagesettings",
            name="home_link_label",
            field=models.CharField(
                default="Zur Startseite",
                max_length=120,
                verbose_name="Beschriftung des Startseitenlinks",
            ),
        ),
        migrations.AddField(
            model_name="portfoliositesettings",
            name="about_label",
            field=models.CharField(
                default="Über mich", max_length=80, verbose_name="Über mich"
            ),
        ),
        migrations.AddField(
            model_name="portfoliositesettings",
            name="all_projects_label",
            field=models.CharField(
                default="Alle Projekte",
                max_length=120,
                verbose_name="Alle Projekte",
            ),
        ),
        migrations.AddField(
            model_name="portfoliositesettings",
            name="case_study_label",
            field=models.CharField(
                default="Case Study", max_length=80, verbose_name="Case Study"
            ),
        ),
        migrations.AddField(
            model_name="portfoliositesettings",
            name="clients_label",
            field=models.CharField(
                default="Kunden", max_length=80, verbose_name="Kunden"
            ),
        ),
        migrations.AddField(
            model_name="portfoliositesettings",
            name="contact_label",
            field=models.CharField(
                default="Kontakt", max_length=80, verbose_name="Kontakt"
            ),
        ),
        migrations.AddField(
            model_name="portfoliositesettings",
            name="footer_pages_heading",
            field=models.CharField(
                default="Seite",
                max_length=80,
                verbose_name="Footer: Seitenüberschrift",
            ),
        ),
        migrations.AddField(
            model_name="portfoliositesettings",
            name="gallery_label",
            field=models.CharField(
                default="Galerie", max_length=80, verbose_name="Galerie"
            ),
        ),
        migrations.AddField(
            model_name="portfoliositesettings",
            name="project_challenge_heading",
            field=models.CharField(
                default="Die Aufgabe",
                max_length=120,
                verbose_name="Projekt: Aufgaben-Überschrift",
            ),
        ),
        migrations.AddField(
            model_name="portfoliositesettings",
            name="project_kicker",
            field=models.CharField(
                default="Projekt",
                max_length=80,
                verbose_name="Projekt: Zählerbezeichnung",
            ),
        ),
        migrations.AddField(
            model_name="portfoliositesettings",
            name="project_live_link_label",
            field=models.CharField(
                default="Website ansehen",
                max_length=120,
                verbose_name="Projekt: Link zur Website",
            ),
        ),
        migrations.AddField(
            model_name="portfoliositesettings",
            name="project_meta_category_label",
            field=models.CharField(
                default="Bereich",
                max_length=80,
                verbose_name="Projekt: Bereich",
            ),
        ),
        migrations.AddField(
            model_name="portfoliositesettings",
            name="project_meta_client_label",
            field=models.CharField(
                default="Kunde",
                max_length=80,
                verbose_name="Projekt: Kunde",
            ),
        ),
        migrations.AddField(
            model_name="portfoliositesettings",
            name="project_meta_services_label",
            field=models.CharField(
                default="Leistungen",
                max_length=80,
                verbose_name="Projekt: Leistungen",
            ),
        ),
        migrations.AddField(
            model_name="portfoliositesettings",
            name="project_meta_year_label",
            field=models.CharField(
                default="Jahr",
                max_length=80,
                verbose_name="Projekt: Jahr",
            ),
        ),
        migrations.AddField(
            model_name="portfoliositesettings",
            name="project_results_heading",
            field=models.CharField(
                default="Was bleibt.",
                max_length=120,
                verbose_name="Projekt: Ergebnis-Überschrift",
            ),
        ),
        migrations.AddField(
            model_name="portfoliositesettings",
            name="project_solution_heading",
            field=models.CharField(
                default="Die Lösung",
                max_length=120,
                verbose_name="Projekt: Lösungs-Überschrift",
            ),
        ),
        migrations.AddField(
            model_name="portfoliositesettings",
            name="project_statement_heading",
            field=models.CharField(
                default="Das Projekt",
                max_length=120,
                verbose_name="Projekt: Statement-Überschrift",
            ),
        ),
        migrations.AddField(
            model_name="portfoliositesettings",
            name="project_testimonial_label",
            field=models.CharField(
                default="Rückmeldung",
                max_length=120,
                verbose_name="Projekt: Testimonial-Rubrik",
            ),
        ),
        migrations.AddField(
            model_name="portfoliositesettings",
            name="projects_label",
            field=models.CharField(
                default="Projekte", max_length=80, verbose_name="Projekte"
            ),
        ),
        migrations.AddField(
            model_name="portfoliositesettings",
            name="related_projects_eyebrow",
            field=models.CharField(
                default="Weitere Projekte",
                max_length=120,
                verbose_name="Weitere Projekte: Rubrik",
            ),
        ),
        migrations.AddField(
            model_name="portfoliositesettings",
            name="related_projects_heading",
            field=models.CharField(
                default="Weiterse\xadhen.",
                max_length=120,
                verbose_name="Weitere Projekte: Überschrift",
            ),
        ),
        migrations.AddField(
            model_name="portfoliositesettings",
            name="results_label",
            field=models.CharField(
                default="Ergebnisse", max_length=80, verbose_name="Ergebnisse"
            ),
        ),
        migrations.AddField(
            model_name="portfoliositesettings",
            name="services_label",
            field=models.CharField(
                default="Leistungen", max_length=80, verbose_name="Leistungen"
            ),
        ),
        migrations.AlterField(
            model_name="portfoliositesettings",
            name="contact_email",
            field=models.EmailField(
                default="katharina@wersdoerfer.de",
                help_text=(
                    "Einzige öffentliche E-Mail-Quelle für Header, Menü, "
                    "Startseite, Projektseiten und Rechtstexte."
                ),
                max_length=254,
                verbose_name="Kontaktadresse",
            ),
        ),
        migrations.AlterField(
            model_name="portfolioindexpage",
            name="contact_email",
            field=models.EmailField(
                default="katharina@wersdoerfer.de",
                editable=False,
                help_text=(
                    "Historisches Kompatibilitätsfeld. Die öffentliche "
                    "Kontaktadresse wird ausschließlich in den "
                    "Portfolio-Site-Einstellungen gepflegt."
                ),
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="portfolioindexpage",
            name="hero_heading",
            field=models.CharField(default="Moin", editable=False, max_length=120),
        ),
        migrations.RunPython(
            seed_single_contact_source_and_project_content,
            migrations.RunPython.noop,
        ),
    ]
