# Generated by Django 6.0.5 on 2026-09-15

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0013_project_starter_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectpage",
            name="teaser_text",
            field=wagtail.fields.RichTextField(
                features=["bold", "link", "no-break"],
                help_text=(
                    "Kurzer Projektteaser; Hervorhebungen können fett gesetzt, "
                    "verlinkt oder mit ‚Kein Umbruch‘ als zusammenhängender Begriff "
                    "geschützt werden."
                ),
                max_length=320,
                verbose_name="Teasertext",
            ),
        ),
    ]
