# Generated by Django 6.0.5 on 2026-09-15

import homepage.portfolio.models
import wagtail.fields
from django.db import migrations, models

from ._legal_defaults_v1 import (
    default_imprint_sections,
    default_privacy_sections,
)


def rename_default_results_label(apps, schema_editor):
    PortfolioSiteSettings = apps.get_model("portfolio", "PortfolioSiteSettings")
    database = schema_editor.connection.alias if schema_editor else "default"
    PortfolioSiteSettings.objects.using(database).filter(
        results_label="Ergebnisse"
    ).update(results_label="Mehrwert")
    PortfolioSiteSettings.objects.using(database).filter(
        project_testimonial_label="Rückmeldung"
    ).update(project_testimonial_label="Kundenstimmen")


def restore_default_results_label(apps, schema_editor):
    PortfolioSiteSettings = apps.get_model("portfolio", "PortfolioSiteSettings")
    database = schema_editor.connection.alias if schema_editor else "default"
    PortfolioSiteSettings.objects.using(database).filter(
        results_label="Mehrwert"
    ).update(results_label="Ergebnisse")
    PortfolioSiteSettings.objects.using(database).filter(
        project_testimonial_label="Kundenstimmen"
    ).update(project_testimonial_label="Rückmeldung")


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0014_project_teaser_rich_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfoliositesettings",
            name="project_results_heading",
            field=models.CharField(
                default="Was bleibt.",
                max_length=120,
                verbose_name="Projekt: Mehrwert-Überschrift",
            ),
        ),
        migrations.AlterField(
            model_name="portfoliositesettings",
            name="project_testimonial_label",
            field=models.CharField(
                default="Kundenstimmen",
                max_length=120,
                verbose_name="Projekt: Kundenstimmen-Rubrik",
            ),
        ),
        migrations.AlterField(
            model_name="portfoliositesettings",
            name="results_label",
            field=models.CharField(
                default="Mehrwert", max_length=80, verbose_name="Mehrwert"
            ),
        ),
        migrations.RunPython(
            rename_default_results_label,
            restore_default_results_label,
        ),
        migrations.AlterField(
            model_name="legalpagesettings",
            name="imprint_sections",
            field=wagtail.fields.StreamField(
                [("section", 5)],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Überschrift", "max_length": 160},
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "no-break"],
                            "label": "Absatz",
                        },
                    ),
                    2: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "no-break"],
                            "label": "Adresse",
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Stand oder Hinweis", "max_length": 240},
                    ),
                    4: (
                        "wagtail.blocks.StreamBlock",
                        [[("paragraph", 1), ("address", 2), ("note", 3)]],
                        {"label": "Text"},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 0), ("copy", 4)]],
                        {},
                    ),
                },
                default=default_imprint_sections,
                verbose_name="Impressum: Abschnitte",
            ),
        ),
        migrations.AlterField(
            model_name="legalpagesettings",
            name="privacy_sections",
            field=wagtail.fields.StreamField(
                [("section", 5)],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Überschrift", "max_length": 160},
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "no-break"],
                            "label": "Absatz",
                        },
                    ),
                    2: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "no-break"],
                            "label": "Adresse",
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Stand oder Hinweis", "max_length": 240},
                    ),
                    4: (
                        "wagtail.blocks.StreamBlock",
                        [[("paragraph", 1), ("address", 2), ("note", 3)]],
                        {"label": "Text"},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 0), ("copy", 4)]],
                        {},
                    ),
                },
                default=default_privacy_sections,
                verbose_name="Datenschutz: Abschnitte",
            ),
        ),
        migrations.AlterField(
            model_name="projectpage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("statement", 1),
                    ("challenge_solution", 4),
                    ("full_width_image", 7),
                    ("image_pair", 10),
                    ("portrait_duo", 10),
                    ("gallery", 14),
                    ("stats", 19),
                    ("testimonial", 23),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "no-break"],
                            "label": "Text",
                        },
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("text", 0)]], {}),
                    2: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "link",
                                "no-break",
                            ],
                            "label": "Aufgabe",
                        },
                    ),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "link",
                                "no-break",
                            ],
                            "label": "Lösung",
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("challenge", 2), ("solution", 3)]],
                        {},
                    ),
                    5: ("wagtail.images.blocks.ImageBlock", [], {"label": "Bild"}),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "Bildunterschrift",
                            "max_length": 240,
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 5), ("caption", 6)]],
                        {},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 5), ("caption", 6)]],
                        {"label": "Bild links"},
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 5), ("caption", 6)]],
                        {"label": "Bild rechts"},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("left", 8), ("right", 9)]],
                        {},
                    ),
                    11: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": (
                                "Beginnt eine eigene, vollbreite Galeriezeile."
                            ),
                            "label": "Großes Motiv",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 5), ("caption", 6), ("large", 11)]],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.ListBlock",
                        (12,),
                        {
                            "help_text": (
                                "Mindestens zwei Bilder; die Reihenfolge kann frei "
                                "geändert werden."
                            ),
                            "label": "Bilder",
                            "min_num": 2,
                        },
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("images", 13)]],
                        {},
                    ),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Wert", "max_length": 80},
                    ),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Bezeichnung", "max_length": 160},
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("value", 15), ("label", 16)]],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.ListBlock",
                        (17,),
                        {"label": "Mehrwert", "min_num": 1},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("items", 18)]],
                        {},
                    ),
                    20: ("wagtail.blocks.TextBlock", (), {"label": "Zitat"}),
                    21: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Name", "max_length": 120},
                    ),
                    22: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Rolle", "max_length": 160, "required": False},
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 20), ("name", 21), ("role", 22)]],
                        {},
                    ),
                },
                default=homepage.portfolio.models.default_project_content,
                verbose_name="Projektinhalt",
            ),
        ),
    ]
