# Generated by Django 6.0.5 on 2026-09-15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("portfolio", "0015_project_value_labels")]

    operations = [
        migrations.AddField(
            model_name="projectpage",
            name="live_link_label",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    "Optionaler Text für den Link zur Projektwebsite. Leer lassen, "
                    "um den globalen Standard zu verwenden."
                ),
                max_length=120,
                verbose_name="Text des Website-Buttons",
            ),
        ),
    ]
