# Generated by Django 6.0.5 on 2026-09-15

import django.db.models.deletion
from django.db import migrations, models


LEGACY_CATEGORIES = {
    "web": "Web",
    "digital": "Digital",
    "print": "Print",
    "illustration": "Illustration",
}


def category_name(legacy_value):
    """Return a readable category name for known and unexpected legacy values."""

    if legacy_value in LEGACY_CATEGORIES:
        return LEGACY_CATEGORIES[legacy_value]
    if legacy_value:
        return str(legacy_value).replace("-", " ").replace("_", " ").title()
    return "Ohne Kategorie"


def migrate_project_categories(apps, schema_editor):
    """Create shared categories and preserve both live pages and revisions."""

    ProjectCategory = apps.get_model("portfolio", "ProjectCategory")
    ProjectPage = apps.get_model("portfolio", "ProjectPage")
    Revision = apps.get_model("wagtailcore", "Revision")
    database = schema_editor.connection.alias

    category_ids = {}

    def category_id_for(legacy_value):
        if legacy_value in category_ids:
            return category_ids[legacy_value]
        category, _created = ProjectCategory.objects.using(database).get_or_create(
            name=category_name(legacy_value)
        )
        category_ids[legacy_value] = category.pk
        return category.pk

    for legacy_value in LEGACY_CATEGORIES:
        category_id_for(legacy_value)

    projects = list(ProjectPage.objects.using(database).all())
    for project in projects:
        project.category_id = category_id_for(project.category_legacy)
    ProjectPage.objects.using(database).bulk_update(projects, ["category"])

    revisions = Revision.objects.using(database).filter(
        content_type__app_label="portfolio",
        content_type__model="projectpage",
    )
    for revision in revisions.iterator():
        content = dict(revision.content)
        legacy_value = content.get("category_legacy") or content.get("category", "")
        content["category_legacy"] = legacy_value
        content["category"] = category_id_for(legacy_value)
        revision.content = content
        revision.save(update_fields=["content"])


def restore_fixed_project_categories(apps, schema_editor):
    """Restore legacy category values when rolling the schema back."""

    ProjectCategory = apps.get_model("portfolio", "ProjectCategory")
    ProjectPage = apps.get_model("portfolio", "ProjectPage")
    Revision = apps.get_model("wagtailcore", "Revision")
    database = schema_editor.connection.alias

    legacy_by_name = {name: value for value, name in LEGACY_CATEGORIES.items()}
    legacy_by_id = {
        category.pk: legacy_by_name.get(category.name, "")
        for category in ProjectCategory.objects.using(database).all()
    }

    projects = list(ProjectPage.objects.using(database).all())
    for project in projects:
        if not project.category_legacy:
            project.category_legacy = legacy_by_id.get(project.category_id, "")
    ProjectPage.objects.using(database).bulk_update(projects, ["category_legacy"])

    revisions = Revision.objects.using(database).filter(
        content_type__app_label="portfolio",
        content_type__model="projectpage",
    )
    for revision in revisions.iterator():
        content = dict(revision.content)
        legacy_value = content.get("category_legacy", "")
        if not legacy_value:
            legacy_value = legacy_by_id.get(content.get("category"), "")
        content["category"] = legacy_value
        content.pop("category_legacy", None)
        revision.content = content
        revision.save(update_fields=["content"])


class Migration(migrations.Migration):
    dependencies = [("portfolio", "0016_project_live_link_label")]

    operations = [
        migrations.CreateModel(
            name="ProjectCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=80, unique=True, verbose_name="Name"),
                ),
            ],
            options={
                "verbose_name": "Projektkategorie",
                "verbose_name_plural": "Projektkategorien",
                "ordering": ["name"],
            },
        ),
        migrations.RenameField(
            model_name="projectpage",
            old_name="category",
            new_name="category_legacy",
        ),
        migrations.AlterField(
            model_name="projectpage",
            name="category_legacy",
            field=models.CharField(
                blank=True,
                choices=[
                    ("web", "Web"),
                    ("digital", "Digital"),
                    ("print", "Print"),
                    ("illustration", "Illustration"),
                ],
                default="",
                editable=False,
                help_text=(
                    "Temporäres Altfeld; wird nach geprüfter Inhaltsmigration entfernt."
                ),
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="projectpage",
            name="category",
            field=models.ForeignKey(
                help_text=(
                    "Zentrale Projektkategorie. Neue Kategorien können direkt im "
                    "Auswahlfenster oder über ‚Projekte → Kategorien‘ angelegt werden."
                ),
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projects",
                to="portfolio.projectcategory",
                verbose_name="Bereich",
            ),
        ),
        migrations.RunPython(
            migrate_project_categories,
            restore_fixed_project_categories,
        ),
        migrations.AlterField(
            model_name="projectpage",
            name="category",
            field=models.ForeignKey(
                help_text=(
                    "Zentrale Projektkategorie. Neue Kategorien können direkt im "
                    "Auswahlfenster oder über ‚Projekte → Kategorien‘ angelegt werden."
                ),
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projects",
                to="portfolio.projectcategory",
                verbose_name="Bereich",
            ),
        ),
    ]
