# Generated by Django 6.0.5 on 2026-09-18

import django.core.validators
from django.db import migrations, models

import homepage.portfolio.models


class Migration(migrations.Migration):
    dependencies = [("portfolio", "0017_editable_project_categories")]

    operations = [
        migrations.AlterField(
            model_name="projectpage",
            name="year",
            field=models.PositiveSmallIntegerField(
                help_text="Bei einem Zeitraum das erste Jahr eintragen.",
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(
                        homepage.portfolio.models.current_year
                    ),
                ],
                verbose_name="Jahr / Startjahr",
            ),
        ),
        migrations.AddField(
            model_name="projectpage",
            name="end_year",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text=(
                    "Nur bei mehrjährigen Projekten ausfüllen. Die Ausgabe erfolgt "
                    "automatisch als Zeitraum, zum Beispiel 2021–2024."
                ),
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(
                        homepage.portfolio.models.current_year
                    ),
                ],
                verbose_name="Endjahr (optional)",
            ),
        ),
    ]
