# Generated by Django 6.0.5 on 2026-09-21

from collections import defaultdict

from django.db import migrations, models
from django.db.models import Q


def seed_homepage_hero_tiles(apps, schema_editor):
    """Preserve the approved positional hero rhythm as explicit project data."""

    ProjectPage = apps.get_model("portfolio", "ProjectPage")
    PageViewRestriction = apps.get_model("wagtailcore", "PageViewRestriction")
    Revision = apps.get_model("wagtailcore", "Revision")
    database = schema_editor.connection.alias

    projects_by_parent = defaultdict(list)
    projects = ProjectPage.objects.using(database).filter(live=True).order_by("path")
    private_paths = PageViewRestriction.objects.using(database).values_list(
        "page__path", flat=True
    )
    private_pages = Q()
    for private_path in private_paths:
        private_pages |= Q(path__startswith=private_path)
    if private_pages:
        projects = projects.exclude(private_pages)

    for project in projects:
        step_length, remainder = divmod(len(project.path), project.depth)
        if remainder or not step_length:
            raise RuntimeError(
                f"Cannot derive the tree path step for ProjectPage {project.pk}."
            )
        projects_by_parent[project.path[:-step_length]].append(project)

    hero_ids = set()
    changed_projects = []
    for siblings in projects_by_parent.values():
        for position, project in enumerate(siblings, start=1):
            project.homepage_is_hero = position == 1 or position % 6 in {0, 1}
            if project.homepage_is_hero:
                hero_ids.add(project.pk)
            changed_projects.append(project)

    if changed_projects:
        ProjectPage.objects.using(database).bulk_update(
            changed_projects, ["homepage_is_hero"]
        )

    revisions = Revision.objects.using(database).filter(
        content_type__app_label="portfolio",
        content_type__model="projectpage",
    )
    for revision in revisions.iterator():
        content = dict(revision.content)
        content["homepage_is_hero"] = content.get("pk") in hero_ids
        revision.content = content
        revision.save(using=database, update_fields=["content"])


def remove_homepage_hero_tiles_from_revisions(apps, schema_editor):
    """Keep historic revision JSON compatible when reversing the schema."""

    Revision = apps.get_model("wagtailcore", "Revision")
    database = schema_editor.connection.alias
    revisions = Revision.objects.using(database).filter(
        content_type__app_label="portfolio",
        content_type__model="projectpage",
    )
    for revision in revisions.iterator():
        content = dict(revision.content)
        content.pop("homepage_is_hero", None)
        revision.content = content
        revision.save(using=database, update_fields=["content"])


class Migration(migrations.Migration):
    dependencies = [("portfolio", "0018_project_period")]

    operations = [
        migrations.AddField(
            model_name="projectpage",
            name="homepage_is_hero",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Stellt das Projekt im Desktop-Raster groß und quer im Format "
                    "21:9 dar. Mobil bleibt das erste Projekt der sortierten "
                    "Reihenfolge der große 16:9-Einstieg; alle weiteren Projekte "
                    "laufen im einheitlichen Reel."
                ),
                verbose_name="Hero-Kachel auf der Startseite",
            ),
        ),
        migrations.RunPython(
            seed_homepage_hero_tiles,
            remove_homepage_hero_tiles_from_revisions,
        ),
    ]
