# Generated by Django 6.0.5 on 2026-09-21

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0019_homepage_project_tiles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolioindexpage",
            name="about_heading",
            field=models.CharField(
                default="Über mich",
                editable=False,
                help_text=(
                    "Historisches Kompatibilitätsfeld. Die sichtbaren Inhalte werden "
                    "über die editierbaren Über-mich-Einträge gepflegt."
                ),
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="portfolioindexpage",
            name="about_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                editable=False,
                help_text=(
                    "Historisches Kompatibilitätsfeld. Die sichtbaren Inhalte werden "
                    "über die editierbaren Über-mich-Einträge gepflegt."
                ),
            ),
        ),
        migrations.AlterField(
            model_name="portfolioindexpage",
            name="contact_heading",
            field=models.CharField(
                default="Lass uns sprechen",
                editable=False,
                help_text=(
                    "Historisches Kompatibilitätsfeld. Die sichtbare "
                    "Kontaktüberschrift wird über die getrennten Kontaktfelder gepflegt."
                ),
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="portfolioindexpage",
            name="projects_annotation",
            field=models.CharField(
                default="recent work", editable=False, max_length=120
            ),
        ),
        migrations.AlterField(
            model_name="portfolioindexpage",
            name="services_annotation",
            field=models.CharField(
                default="let's talk about", editable=False, max_length=120
            ),
        ),
        migrations.AlterField(
            model_name="portfolioindexpage",
            name="about_annotation",
            field=models.CharField(
                default="that's me", editable=False, max_length=120
            ),
        ),
        migrations.AlterField(
            model_name="portfolioindexpage",
            name="clients_annotation",
            field=models.CharField(
                default="together", editable=False, max_length=120
            ),
        ),
        migrations.AlterField(
            model_name="portfolioindexpage",
            name="contact_annotation",
            field=models.CharField(
                default="tell me more", editable=False, max_length=120
            ),
        ),
    ]
