# Generated by Django 6.0.5 on 2026-09-21

from django.db import migrations, models

import homepage.portfolio.models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0020_hide_legacy_homepage_copy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfoliositesettings",
            name="imprint_url",
            field=models.CharField(
                default="/impressum/",
                editable=False,
                help_text=(
                    "Mit / beginnender interner Pfad oder vollständige HTTP(S)-URL."
                ),
                max_length=255,
                validators=[
                    homepage.portfolio.models.validate_internal_path_or_http_url
                ],
                verbose_name="Impressum",
            ),
        ),
        migrations.AlterField(
            model_name="portfoliositesettings",
            name="privacy_url",
            field=models.CharField(
                default="/datenschutz/",
                editable=False,
                help_text=(
                    "Mit / beginnender interner Pfad oder vollständige HTTP(S)-URL."
                ),
                max_length=255,
                validators=[
                    homepage.portfolio.models.validate_internal_path_or_http_url
                ],
                verbose_name="Datenschutz",
            ),
        ),
    ]
