# Generated by Django 6.0.5 on 2026-09-21

import html
import re
import uuid

import homepage.portfolio.models
import wagtail.fields
from django.db import migrations
from django.utils.html import strip_tags


LEGACY_PLACEHOLDER_EMAIL = "portfolio-contact@example.invalid"
LEGACY_DEFAULT_EMAIL = "katharina@wersdoerfer.de"
MAIL_LINK = re.compile(
    r"<a\b[^>]*\bhref=([\"'])mailto:(?P<address>[^\"']+)\1[^>]*>"
    r"(?P<label>.*?)</a>",
    flags=re.IGNORECASE | re.DOTALL,
)
OUTER_PARAGRAPH = re.compile(
    r"^\s*<p>(?P<body>(?:(?!</?p(?:\s|>)).)*)</p>\s*$",
    flags=re.IGNORECASE | re.DOTALL,
)
ADDRESS_SEPARATOR = re.compile(r"<br\s*/?>\s*<br\s*/?>", re.IGNORECASE)
CONTACT_FIELD_LIMITS = {"prefix": 240, "label": 160, "suffix": 120}
SPLIT_CONTACT_NAMESPACE = uuid.UUID("a54ae742-e224-43dd-b0d8-f28599fbd68e")


def _split_contact_id(address_id):
    """Return the reversible marker ID for a contact split from an address."""

    return str(uuid.uuid5(SPLIT_CONTACT_NAMESPACE, str(address_id)))


def _plain_contact_value(value, max_length):
    """Return a CharBlock-safe value without discarding authored markup."""

    source = str(value or "")
    if strip_tags(source) != source:
        return None
    plain = html.unescape(source).strip()
    if len(plain) > max_length:
        return None
    return plain


def _contact_parts(source, site_email):
    paragraph = OUTER_PARAGRAPH.fullmatch(source or "")
    if paragraph is None:
        return None
    body = paragraph.group("body")
    matches = list(MAIL_LINK.finditer(body))
    if len(matches) != 1:
        return None

    match = matches[0]
    address = match.group("address").strip()
    label = _plain_contact_value(
        match.group("label"), CONTACT_FIELD_LIMITS["label"]
    )
    suffix = _plain_contact_value(
        body[match.end() :], CONTACT_FIELD_LIMITS["suffix"]
    )
    if label is None or suffix is None:
        return None
    known_address = address.casefold() in {
        LEGACY_PLACEHOLDER_EMAIL.casefold(),
        LEGACY_DEFAULT_EMAIL.casefold(),
        (site_email or "").casefold(),
    }
    if not known_address:
        return None

    prefix_html = body[: match.start()]
    visible_label = "" if label in {"[globale Kontaktadresse]", address} else label
    return prefix_html, visible_label, suffix


def _migrate_stream(raw_sections, site_email):
    changed = False
    for section in raw_sections or []:
        if not isinstance(section, dict) or section.get("type") != "section":
            continue
        section_value = section.get("value")
        if not isinstance(section_value, dict):
            continue
        copy = section_value.get("copy")
        if not isinstance(copy, list):
            continue
        migrated_copy = []
        section_changed = False
        for item in copy:
            if not isinstance(item, dict) or item.get("type") not in {
                "paragraph",
                "address",
            }:
                migrated_copy.append(item)
                continue
            parts = _contact_parts(str(item.get("value") or ""), site_email)
            if parts is None:
                migrated_copy.append(item)
                continue

            prefix_html, label, suffix = parts
            if item["type"] == "address":
                separators = list(ADDRESS_SEPARATOR.finditer(prefix_html))
                if not separators:
                    migrated_copy.append(item)
                    continue
                separator = separators[-1]
                postal_address = prefix_html[: separator.start()]
                contact_prefix = _plain_contact_value(
                    prefix_html[separator.end() :],
                    CONTACT_FIELD_LIMITS["prefix"],
                )
                if not postal_address or contact_prefix is None:
                    migrated_copy.append(item)
                    continue
                address_id = item.get("id") or str(uuid.uuid4())
                migrated_copy.append(
                    {
                        **item,
                        "value": f"<p>{postal_address}</p>",
                        "id": address_id,
                    }
                )
                # A deterministic UUID ties this generated contact to the address
                # immediately before it.  The reverse migration can therefore merge
                # only pairs created here, without collapsing an editor-authored
                # address followed by an independent contact block.
                contact_id = _split_contact_id(address_id)
            else:
                contact_prefix = _plain_contact_value(
                    prefix_html, CONTACT_FIELD_LIMITS["prefix"]
                )
                if contact_prefix is None:
                    migrated_copy.append(item)
                    continue
                contact_id = item.get("id") or str(uuid.uuid4())

            migrated_copy.append(
                {
                    "type": "contact",
                    "value": {
                        "prefix": contact_prefix,
                        "label": label,
                        "suffix": suffix,
                    },
                    "id": contact_id,
                }
            )
            section_changed = True
            changed = True
        if section_changed:
            section_value["copy"] = migrated_copy
    return changed


def _restore_stream(raw_sections, site_email):
    changed = False
    for section in raw_sections or []:
        if not isinstance(section, dict) or section.get("type") != "section":
            continue
        section_value = section.get("value")
        if not isinstance(section_value, dict):
            continue
        copy = section_value.get("copy")
        if not isinstance(copy, list):
            continue
        restored = []
        section_changed = False
        for item in copy:
            if not isinstance(item, dict) or item.get("type") != "contact":
                restored.append(item)
                continue
            value = item.get("value") or {}
            prefix = html.escape(str(value.get("prefix") or ""))
            label = html.escape(str(value.get("label") or site_email))
            suffix = html.escape(str(value.get("suffix") or ""))
            email = html.escape(site_email, quote=True)
            contact_body = (
                f'{prefix}{" " if prefix else ""}'
                f'<a href="mailto:{email}">{label}</a>{suffix}'
            )
            previous = restored[-1] if restored else None
            previous_id = previous.get("id") if isinstance(previous, dict) else None
            previous_paragraph = (
                OUTER_PARAGRAPH.fullmatch(str(previous.get("value") or ""))
                if isinstance(previous, dict) and previous.get("type") == "address"
                else None
            )
            if (
                previous_id
                and item.get("id") == _split_contact_id(previous_id)
                and previous_paragraph is not None
            ):
                # Reconstruct the legacy address block rather than changing its
                # structure to an address-plus-paragraph pair on reversal.
                restored[-1] = {
                    **previous,
                    "value": (
                        f"<p>{previous_paragraph.group('body')}<br><br>"
                        f"{contact_body}</p>"
                    ),
                }
            else:
                restored.append(
                    {
                        "type": "paragraph",
                        "value": f"<p>{contact_body}</p>",
                        "id": item.get("id") or str(uuid.uuid4()),
                    }
                )
            section_changed = True
            changed = True
        if section_changed:
            section_value["copy"] = restored
    return changed


def migrate_legal_contacts(apps, schema_editor):
    LegalPageSettings = apps.get_model("portfolio", "LegalPageSettings")
    PortfolioSiteSettings = apps.get_model("portfolio", "PortfolioSiteSettings")
    database = schema_editor.connection.alias if schema_editor else "default"
    emails = dict(
        PortfolioSiteSettings.objects.using(database).values_list(
            "site_id", "contact_email"
        )
    )
    default_email = PortfolioSiteSettings._meta.get_field("contact_email").default

    for settings in LegalPageSettings.objects.using(database).all().iterator():
        update_fields = []
        site_email = emails.get(settings.site_id, default_email)
        for field_name in ("imprint_sections", "privacy_sections"):
            stream = getattr(settings, field_name)
            raw_sections = stream.raw_data
            if _migrate_stream(raw_sections, site_email):
                setattr(settings, field_name, raw_sections)
                update_fields.append(field_name)
        if update_fields:
            settings.save(update_fields=update_fields, using=database)


def restore_embedded_legal_contacts(apps, schema_editor):
    LegalPageSettings = apps.get_model("portfolio", "LegalPageSettings")
    PortfolioSiteSettings = apps.get_model("portfolio", "PortfolioSiteSettings")
    database = schema_editor.connection.alias if schema_editor else "default"
    emails = dict(
        PortfolioSiteSettings.objects.using(database).values_list(
            "site_id", "contact_email"
        )
    )
    default_email = PortfolioSiteSettings._meta.get_field("contact_email").default

    for settings in LegalPageSettings.objects.using(database).all().iterator():
        update_fields = []
        site_email = emails.get(settings.site_id, default_email)
        for field_name in ("imprint_sections", "privacy_sections"):
            raw_sections = getattr(settings, field_name).raw_data
            if _restore_stream(raw_sections, site_email):
                setattr(settings, field_name, raw_sections)
                update_fields.append(field_name)
        if update_fields:
            settings.save(update_fields=update_fields, using=database)


class Migration(migrations.Migration):
    dependencies = [("portfolio", "0021_lock_builtin_legal_destinations")]

    operations = [
        migrations.AlterField(
            model_name="legalpagesettings",
            name="imprint_sections",
            field=wagtail.fields.StreamField(
                [("section", 9)],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Überschrift", "max_length": 160},
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "no-break"],
                            "label": "Absatz",
                        },
                    ),
                    2: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "no-break"],
                            "label": "Adresse",
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Stand oder Hinweis", "max_length": 240},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": (
                                "Zum Beispiel „E-Mail:“; Abstand und globale Adresse "
                                "werden automatisch ergänzt."
                            ),
                            "label": "Text vor dem Link",
                            "max_length": 240,
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": (
                                "Leer lassen, um die globale Kontaktadresse sichtbar "
                                "auszugeben."
                            ),
                            "label": "Abweichender Linktext",
                            "max_length": 160,
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Zum Beispiel ein abschließender Punkt.",
                            "label": "Text nach dem Link",
                            "max_length": 120,
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("prefix", 4), ("label", 5), ("suffix", 6)]],
                        {},
                    ),
                    8: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("paragraph", 1),
                                ("address", 2),
                                ("note", 3),
                                ("contact", 7),
                            ]
                        ],
                        {"label": "Text"},
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 0), ("copy", 8)]],
                        {},
                    ),
                },
                default=homepage.portfolio.models.default_imprint_sections,
                verbose_name="Impressum: Abschnitte",
            ),
        ),
        migrations.AlterField(
            model_name="legalpagesettings",
            name="privacy_sections",
            field=wagtail.fields.StreamField(
                [("section", 9)],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Überschrift", "max_length": 160},
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "no-break"],
                            "label": "Absatz",
                        },
                    ),
                    2: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "no-break"],
                            "label": "Adresse",
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Stand oder Hinweis", "max_length": 240},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": (
                                "Zum Beispiel „E-Mail:“; Abstand und globale Adresse "
                                "werden automatisch ergänzt."
                            ),
                            "label": "Text vor dem Link",
                            "max_length": 240,
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": (
                                "Leer lassen, um die globale Kontaktadresse sichtbar "
                                "auszugeben."
                            ),
                            "label": "Abweichender Linktext",
                            "max_length": 160,
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Zum Beispiel ein abschließender Punkt.",
                            "label": "Text nach dem Link",
                            "max_length": 120,
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("prefix", 4), ("label", 5), ("suffix", 6)]],
                        {},
                    ),
                    8: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("paragraph", 1),
                                ("address", 2),
                                ("note", 3),
                                ("contact", 7),
                            ]
                        ],
                        {"label": "Text"},
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 0), ("copy", 8)]],
                        {},
                    ),
                },
                default=homepage.portfolio.models.default_privacy_sections,
                verbose_name="Datenschutz: Abschnitte",
            ),
        ),
        migrations.RunPython(
            migrate_legal_contacts,
            restore_embedded_legal_contacts,
        ),
    ]
