version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}
  caddy: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    depends_on:
      - postgres
      - redis
    env_file: .env
    command: /gunicorn.sh
    ports:
      - "127.0.0.1:8080:5000"

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file: .env

#  caddy:
#    build:
#      context: .
#      dockerfile: ./compose/production/caddy/Dockerfile
#    depends_on:
#      - django
#    volumes:
#      - caddy:/root/.caddy
#    env_file: .env
#    ports:
#      - "0.0.0.0:81:80"
#      - "0.0.0.0:4444:443"

  redis:
    image: redis:3.0

