# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-16 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='original_height',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='original_width',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='original',
            field=models.ImageField(height_field='original_height', upload_to='blogs_images', width_field='original_width'),
        ),
    ]
