# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-16 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20170916_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='original_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='original_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
