# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-18 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_auto_20170916_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='img_lg',
            field=models.ImageField(blank=True, height_field='lg_height', null=True, upload_to='blogs_images/resized', width_field='lg_width'),
        ),
        migrations.AddField(
            model_name='image',
            name='img_md',
            field=models.ImageField(blank=True, height_field='md_height', null=True, upload_to='blogs_images/resized', width_field='md_width'),
        ),
        migrations.AddField(
            model_name='image',
            name='img_sm',
            field=models.ImageField(blank=True, height_field='sm_height', null=True, upload_to='blogs_images/resized', width_field='sm_width'),
        ),
        migrations.AddField(
            model_name='image',
            name='img_xs',
            field=models.ImageField(blank=True, height_field='xs_height', null=True, upload_to='blogs_images/resized', width_field='xs_width'),
        ),
        migrations.AddField(
            model_name='image',
            name='lg_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='lg_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='md_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='md_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='sm_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='sm_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='xs_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='xs_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='img_xl',
            field=models.ImageField(blank=True, height_field='xl_height', null=True, upload_to='blogs_images/resized', width_field='xl_width'),
        ),
        migrations.AlterField(
            model_name='image',
            name='original',
            field=models.ImageField(height_field='original_height', upload_to='blogs_images/originals', width_field='original_width'),
        ),
    ]
