# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-18 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_auto_20170918_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='portrait',
            field=models.BooleanField(default=False),
        ),
    ]
