# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-18 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_image_portrait'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='BlogImage',
        ),
    ]
