# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-08 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_bloggallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogimage',
            name='full_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogimage',
            name='full_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogimage',
            name='img_full',
            field=models.ImageField(blank=True, height_field='full_height', null=True, upload_to='blogs_images/resized', width_field='full_width'),
        ),
    ]
