# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-24 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_blogmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmedia',
            name='blogpost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='blogs.BlogPost'),
        ),
    ]
