# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-27 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0015_auto_20171024_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='galleries',
            field=models.ManyToManyField(to='blogs.BlogGallery'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='images',
            field=models.ManyToManyField(to='blogs.BlogImage'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='videos',
            field=models.ManyToManyField(to='blogs.BlogVideo'),
        ),
    ]
