# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-30 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0017_auto_20171030_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogvideo',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='blogs_videos/poster/'),
        ),
        migrations.AddField(
            model_name='blogvideo',
            name='poster_seconds',
            field=models.FloatField(default=1),
        ),
    ]
