# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-04 07:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0018_auto_20171030_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogimage',
            name='full_height',
        ),
        migrations.RemoveField(
            model_name='blogimage',
            name='full_width',
        ),
        migrations.RemoveField(
            model_name='blogimage',
            name='img_full',
        ),
        migrations.RemoveField(
            model_name='blogimage',
            name='img_lg',
        ),
        migrations.RemoveField(
            model_name='blogimage',
            name='img_md',
        ),
        migrations.RemoveField(
            model_name='blogimage',
            name='img_sm',
        ),
        migrations.RemoveField(
            model_name='blogimage',
            name='img_xl',
        ),
        migrations.RemoveField(
            model_name='blogimage',
            name='img_xs',
        ),
        migrations.RemoveField(
            model_name='blogimage',
            name='lg_height',
        ),
        migrations.RemoveField(
            model_name='blogimage',
            name='lg_width',
        ),
        migrations.RemoveField(
            model_name='blogimage',
            name='md_height',
        ),
        migrations.RemoveField(
            model_name='blogimage',
            name='md_width',
        ),
        migrations.RemoveField(
            model_name='blogimage',
            name='sm_height',
        ),
        migrations.RemoveField(
            model_name='blogimage',
            name='sm_width',
        ),
        migrations.RemoveField(
            model_name='blogimage',
            name='xl_height',
        ),
        migrations.RemoveField(
            model_name='blogimage',
            name='xl_width',
        ),
        migrations.RemoveField(
            model_name='blogimage',
            name='xs_height',
        ),
        migrations.RemoveField(
            model_name='blogimage',
            name='xs_width',
        ),
    ]
