# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-10 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0021_blogfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
