# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-10 09:04
from __future__ import unicode_literals

from django.db import migrations


def set_pub_date(apps, schema_editor):
    BlogPost = apps.get_model('blogs', 'BlogPost')
    for bp in BlogPost.objects.all():
        bp.pub_date = bp.created if bp.published else None
        bp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0022_blogpost_pub_date'),
    ]

    operations = [
        migrations.RunPython(set_pub_date),
    ]
