# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-10 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0023_auto_20171110_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='published',
        ),
    ]
