# Generated by Django 2.1 on 2018-11-05 12:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0025_blogpost_visible_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='visible_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
