---
- name: Install Astral UV
  hosts: all
  become: yes  # This enables sudo privileges
  tasks:
    - name: Create temporary directory
      tempfile:
        state: directory
      register: temp_dir

    - name: Download and run UV installer script
      shell: curl -LsSf https://astral.sh/uv/install.sh | sh
      args:
        executable: /bin/bash
        chdir: "{{ temp_dir.path }}"
      register: install_result

    - name: Display installation output
      debug:
        var: install_result.stdout_lines

    - name: Find the UV binary
      shell: find ~/.cargo/bin -name uv
      register: uv_binary
      become: no  # Run as the current user, not root

    - name: Copy UV binary to /usr/local/bin
      copy:
        src: "{{ uv_binary.stdout }}"
        dest: /usr/local/bin/uv
        mode: '0755'
        remote_src: yes
      when: uv_binary.stdout != ""

    - name: Verify installation
      command: /usr/local/bin/uv --version
      register: version_output

    - name: Display UV version
      debug:
        var: version_output.stdout

    - name: Clean up temporary directory
      file:
        path: "{{ temp_dir.path }}"
        state: absent
