all:
  vars:
    ansible_connection: ssh
    ansible_ssh_user: root
  hosts:
    production:
      ansible_host: 136.243.145.93  # staging.wersdoerfer.de
  children:
    webservers:
      hosts:
        production:
    database:
      hosts:
        production:
