# Generated by Django 5.1.1 on 2024-09-08 06:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("pronouns", models.CharField(max_length=20)),
                ("tagline", models.CharField(max_length=512)),
                ("about", models.TextField()),
                ("avatar_url", models.URLField()),
                ("avatar_alt", models.CharField(max_length=255)),
                ("location_name", models.CharField(max_length=255)),
                ("location_url", models.URLField()),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("website", models.URLField()),
                ("github", models.URLField()),
                ("linkedin", models.URLField()),
                ("mastodon", models.URLField()),
                ("skills", models.CharField(default="", max_length=512)),
                ("education_school_name", models.CharField(default="", max_length=255)),
                ("education_school_url", models.URLField(blank=True, null=True)),
                (
                    "education_start",
                    models.PositiveIntegerField(
                        default=2016,
                        validators=[
                            django.core.validators.MinValueValidator(1997),
                            django.core.validators.MaxValueValidator(2030),
                        ],
                    ),
                ),
                (
                    "education_end",
                    models.PositiveIntegerField(
                        default=2020,
                        validators=[
                            django.core.validators.MinValueValidator(2001),
                            django.core.validators.MaxValueValidator(2030),
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CVToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token", models.CharField(max_length=255, unique=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("receiver", models.CharField(max_length=255)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="cv_tokens", to="resume.person"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Timeline",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0, help_text="Position of the timeline in the list of timelines.", unique=True
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="timelines", to="resume.person"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimelineEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("company_name", models.CharField(max_length=255)),
                ("company_url", models.URLField(blank=True, null=True)),
                ("role", models.CharField(max_length=255)),
                (
                    "position",
                    models.PositiveIntegerField(default=0, help_text="Position of the entry in the timeline."),
                ),
                (
                    "start",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2000),
                            django.core.validators.MaxValueValidator(2030),
                        ]
                    ),
                ),
                (
                    "end",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2001),
                            django.core.validators.MaxValueValidator(2030),
                        ]
                    ),
                ),
                ("description", models.TextField()),
                ("badges", models.CharField(blank=True, default="", max_length=255)),
                (
                    "timeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="entries", to="resume.timeline"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("url", models.URLField()),
                ("description", models.TextField()),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0, help_text="Position of the project in the list of projects."
                    ),
                ),
                ("badges", models.CharField(blank=True, default="", max_length=512)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="projects", to="resume.person"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("person", "position"), name="unique_project_position")
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="timeline",
            constraint=models.UniqueConstraint(fields=("person", "position"), name="unique_timeline_position"),
        ),
        migrations.AddConstraint(
            model_name="timelineentry",
            constraint=models.UniqueConstraint(fields=("timeline", "position"), name="unique_timeline_entry_position"),
        ),
    ]
